# fly.toml app configuration file generated for syscrack-frontend on 2025-09-13T06:40:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'syscrack-frontend'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
