site_name: Syscrack Manual

theme: lantana

visible_search: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date
  - awesome-pages
  - git-authors:
      show_email_address: true
      count_empty_lines: true
      fallback_to_empty: false
      enabled: true
  - pdf-export:
      verbose: true
      combined: true
      enabled_if_env: ENABLE_PDF_EXPORT

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Workspaces: workspaces.md
  - Development Guide: development.md
  - The Market: market.md

markdown_extensions:
  - lantana
  - lantana.alerts2
  - lantana.selector
  - lantana.extensions.mdx_embedly
  - lantana.extensions.mdx_wsid
  - attr_list
  - lantana.cards
  - lantana.mtables
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - lantana.codeblock_copybtn
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - lantana.mermaid_precompile
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - pymdownx.striphtml
  - lantana.link_opennewtab
  - lantana.alerts
  - lantana.accordion
  - lantana.tabs
